### PR TITLE
fix(EpochTime): fix in decodeTime black/white tolerance interpretation

### PR DESCRIPTION
**Pull request by MathieuPOUX**
Refs: [ENG-837](https://linear.app/ceeblue/issue/ENG-837)

### CODE REVIEW

**Comment by thomasjammet** [comment]
Makes sense, how did you test the code? 
The best would be to generate samples with different colors.

**Comment by imarsv** [comment]
Unfortunately i do not get it. Could you explain me, please. Why:
`pixels[Math.round(i)] = pixel;` more expensive than `const Y = 0.299 * ((pixel >> 16) & 0xff) + 0.587 * ((pixel >> 8) & 0xff) + 0.114 * (pixel & 0xff);`

**Comment by MathieuPOUX** [comment]
> Makes sense, how did you test the code? The best would be to generate samples with different colors.

I have not tested all the color combination, I have tested with Bunny Video that my issue was fixed: when the sky is BLUE  (a code color close to #0000FF) it stops to compute end-to-end latency. Indeed #0000FF is inferior to #333333 (20% superior to #000000), whereas it's not a black color.
image

**Comment by MathieuPOUX** [comment]
And also testing to avoid regression that end-to-end latency continue to work when is really embedded=>
image

**Review by thomasjammet — APPROVED** [review]

**Review by jobl — APPROVED** [review]

**Pull request merged**
